#############################################################################
# Makefile for building: bshuffle
# Generated by qmake (2.01a) (Qt 4.7.3) on: Fri Sep 23 14:12:52 2011
# Project:  bshuffle.pro
# Template: subdirs
# Command: c:\qtsdk\desktop\qt\4.7.3\mingw\bin\qmake.exe -spec ..\..\..\..\QtSDK\Desktop\Qt\4.7.3\mingw\mkspecs\win32-g++ -o Makefile bshuffle.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = c:\qtsdk\desktop\qt\4.7.3\mingw\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = $(COPY)
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = del
SYMLINK       = 
DEL_DIR       = rmdir
MOVE          = move
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
SUBTARGETS    =  \
		sub-libs-bshuffle-session \
		sub-libs-print-settings \
		sub-bshuffle

libs\bshuffle-session\$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) libs\bshuffle-session\ $(MKDIR) libs\bshuffle-session\ 
	cd libs\bshuffle-session\ && $(QMAKE) c:\Src\Personal\qt\bshuffle_proj\libs\bshuffle-session\bshuffle-session.pro -spec c:\QtSDK\Desktop\Qt\4.7.3\mingw\mkspecs\win32-g++ -o $(MAKEFILE)
sub-libs-bshuffle-session-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) libs\bshuffle-session\ $(MKDIR) libs\bshuffle-session\ 
	cd libs\bshuffle-session\ && $(QMAKE) c:\Src\Personal\qt\bshuffle_proj\libs\bshuffle-session\bshuffle-session.pro -spec c:\QtSDK\Desktop\Qt\4.7.3\mingw\mkspecs\win32-g++ -o $(MAKEFILE)
sub-libs-bshuffle-session: libs\bshuffle-session\$(MAKEFILE) FORCE
	cd libs\bshuffle-session\ && $(MAKE) -f $(MAKEFILE)
sub-libs-bshuffle-session-make_default: libs\bshuffle-session\$(MAKEFILE) FORCE
	cd libs\bshuffle-session\ && $(MAKE) -f $(MAKEFILE) 
sub-libs-bshuffle-session-make_first: libs\bshuffle-session\$(MAKEFILE) FORCE
	cd libs\bshuffle-session\ && $(MAKE) -f $(MAKEFILE) first
sub-libs-bshuffle-session-all: libs\bshuffle-session\$(MAKEFILE) FORCE
	cd libs\bshuffle-session\ && $(MAKE) -f $(MAKEFILE) all
sub-libs-bshuffle-session-clean: libs\bshuffle-session\$(MAKEFILE) FORCE
	cd libs\bshuffle-session\ && $(MAKE) -f $(MAKEFILE) clean
sub-libs-bshuffle-session-distclean: libs\bshuffle-session\$(MAKEFILE) FORCE
	cd libs\bshuffle-session\ && $(MAKE) -f $(MAKEFILE) distclean
sub-libs-bshuffle-session-install_subtargets: libs\bshuffle-session\$(MAKEFILE) FORCE
	cd libs\bshuffle-session\ && $(MAKE) -f $(MAKEFILE) install
sub-libs-bshuffle-session-uninstall_subtargets: libs\bshuffle-session\$(MAKEFILE) FORCE
	cd libs\bshuffle-session\ && $(MAKE) -f $(MAKEFILE) uninstall
libs\print-settings\$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) libs\print-settings\ $(MKDIR) libs\print-settings\ 
	cd libs\print-settings\ && $(QMAKE) c:\Src\Personal\qt\bshuffle_proj\libs\print-settings\print-settings.pro -spec c:\QtSDK\Desktop\Qt\4.7.3\mingw\mkspecs\win32-g++ -o $(MAKEFILE)
sub-libs-print-settings-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) libs\print-settings\ $(MKDIR) libs\print-settings\ 
	cd libs\print-settings\ && $(QMAKE) c:\Src\Personal\qt\bshuffle_proj\libs\print-settings\print-settings.pro -spec c:\QtSDK\Desktop\Qt\4.7.3\mingw\mkspecs\win32-g++ -o $(MAKEFILE)
sub-libs-print-settings: libs\print-settings\$(MAKEFILE) FORCE
	cd libs\print-settings\ && $(MAKE) -f $(MAKEFILE)
sub-libs-print-settings-make_default: libs\print-settings\$(MAKEFILE) FORCE
	cd libs\print-settings\ && $(MAKE) -f $(MAKEFILE) 
sub-libs-print-settings-make_first: libs\print-settings\$(MAKEFILE) FORCE
	cd libs\print-settings\ && $(MAKE) -f $(MAKEFILE) first
sub-libs-print-settings-all: libs\print-settings\$(MAKEFILE) FORCE
	cd libs\print-settings\ && $(MAKE) -f $(MAKEFILE) all
sub-libs-print-settings-clean: libs\print-settings\$(MAKEFILE) FORCE
	cd libs\print-settings\ && $(MAKE) -f $(MAKEFILE) clean
sub-libs-print-settings-distclean: libs\print-settings\$(MAKEFILE) FORCE
	cd libs\print-settings\ && $(MAKE) -f $(MAKEFILE) distclean
sub-libs-print-settings-install_subtargets: libs\print-settings\$(MAKEFILE) FORCE
	cd libs\print-settings\ && $(MAKE) -f $(MAKEFILE) install
sub-libs-print-settings-uninstall_subtargets: libs\print-settings\$(MAKEFILE) FORCE
	cd libs\print-settings\ && $(MAKE) -f $(MAKEFILE) uninstall
bshuffle\$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) bshuffle\ $(MKDIR) bshuffle\ 
	cd bshuffle\ && $(QMAKE) c:\Src\Personal\qt\bshuffle_proj\bshuffle\bshuffle.pro -spec c:\QtSDK\Desktop\Qt\4.7.3\mingw\mkspecs\win32-g++ -o $(MAKEFILE)
sub-bshuffle-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) bshuffle\ $(MKDIR) bshuffle\ 
	cd bshuffle\ && $(QMAKE) c:\Src\Personal\qt\bshuffle_proj\bshuffle\bshuffle.pro -spec c:\QtSDK\Desktop\Qt\4.7.3\mingw\mkspecs\win32-g++ -o $(MAKEFILE)
sub-bshuffle: bshuffle\$(MAKEFILE) FORCE
	cd bshuffle\ && $(MAKE) -f $(MAKEFILE)
sub-bshuffle-make_default: bshuffle\$(MAKEFILE) FORCE
	cd bshuffle\ && $(MAKE) -f $(MAKEFILE) 
sub-bshuffle-make_first: bshuffle\$(MAKEFILE) FORCE
	cd bshuffle\ && $(MAKE) -f $(MAKEFILE) first
sub-bshuffle-all: bshuffle\$(MAKEFILE) FORCE
	cd bshuffle\ && $(MAKE) -f $(MAKEFILE) all
sub-bshuffle-clean: bshuffle\$(MAKEFILE) FORCE
	cd bshuffle\ && $(MAKE) -f $(MAKEFILE) clean
sub-bshuffle-distclean: bshuffle\$(MAKEFILE) FORCE
	cd bshuffle\ && $(MAKE) -f $(MAKEFILE) distclean
sub-bshuffle-install_subtargets: bshuffle\$(MAKEFILE) FORCE
	cd bshuffle\ && $(MAKE) -f $(MAKEFILE) install
sub-bshuffle-uninstall_subtargets: bshuffle\$(MAKEFILE) FORCE
	cd bshuffle\ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: bshuffle.pro  ../../../../QtSDK/Desktop/Qt/4.7.3/mingw/mkspecs/win32-g++/qmake.conf ../../../../QtSDK/Desktop/Qt/4.7.3/mingw/mkspecs/qconfig.pri \
		../../../../QtSDK/Desktop/Qt/4.7.3/mingw/mkspecs/modules/qt_webkit_version.pri \
		../../../../QtSDK/Desktop/Qt/4.7.3/mingw/mkspecs/features/qt_functions.prf \
		../../../../QtSDK/Desktop/Qt/4.7.3/mingw/mkspecs/features/qt_config.prf \
		../../../../QtSDK/Desktop/Qt/4.7.3/mingw/mkspecs/features/exclusive_builds.prf \
		../../../../QtSDK/Desktop/Qt/4.7.3/mingw/mkspecs/features/default_pre.prf \
		../../../../QtSDK/Desktop/Qt/4.7.3/mingw/mkspecs/features/win32/default_pre.prf \
		../../../../QtSDK/Desktop/Qt/4.7.3/mingw/mkspecs/features/debug.prf \
		../../../../QtSDK/Desktop/Qt/4.7.3/mingw/mkspecs/features/debug_and_release.prf \
		../../../../QtSDK/Desktop/Qt/4.7.3/mingw/mkspecs/features/default_post.prf \
		../../../../QtSDK/Desktop/Qt/4.7.3/mingw/mkspecs/features/win32/default_post.prf \
		../../../../QtSDK/Desktop/Qt/4.7.3/mingw/mkspecs/features/win32/rtti.prf \
		../../../../QtSDK/Desktop/Qt/4.7.3/mingw/mkspecs/features/win32/exceptions.prf \
		../../../../QtSDK/Desktop/Qt/4.7.3/mingw/mkspecs/features/win32/stl.prf \
		../../../../QtSDK/Desktop/Qt/4.7.3/mingw/mkspecs/features/shared.prf \
		../../../../QtSDK/Desktop/Qt/4.7.3/mingw/mkspecs/features/warn_on.prf \
		../../../../QtSDK/Desktop/Qt/4.7.3/mingw/mkspecs/features/qt.prf \
		../../../../QtSDK/Desktop/Qt/4.7.3/mingw/mkspecs/features/win32/thread.prf \
		../../../../QtSDK/Desktop/Qt/4.7.3/mingw/mkspecs/features/moc.prf \
		../../../../QtSDK/Desktop/Qt/4.7.3/mingw/mkspecs/features/win32/windows.prf \
		../../../../QtSDK/Desktop/Qt/4.7.3/mingw/mkspecs/features/resources.prf \
		../../../../QtSDK/Desktop/Qt/4.7.3/mingw/mkspecs/features/uic.prf \
		../../../../QtSDK/Desktop/Qt/4.7.3/mingw/mkspecs/features/yacc.prf \
		../../../../QtSDK/Desktop/Qt/4.7.3/mingw/mkspecs/features/lex.prf \
		../../../../QtSDK/Desktop/Qt/4.7.3/mingw/mkspecs/features/include_source_dir.prf
	$(QMAKE) -spec ..\..\..\..\QtSDK\Desktop\Qt\4.7.3\mingw\mkspecs\win32-g++ -o Makefile bshuffle.pro
..\..\..\..\QtSDK\Desktop\Qt\4.7.3\mingw\mkspecs\qconfig.pri:
..\..\..\..\QtSDK\Desktop\Qt\4.7.3\mingw\mkspecs\modules\qt_webkit_version.pri:
..\..\..\..\QtSDK\Desktop\Qt\4.7.3\mingw\mkspecs\features\qt_functions.prf:
..\..\..\..\QtSDK\Desktop\Qt\4.7.3\mingw\mkspecs\features\qt_config.prf:
..\..\..\..\QtSDK\Desktop\Qt\4.7.3\mingw\mkspecs\features\exclusive_builds.prf:
..\..\..\..\QtSDK\Desktop\Qt\4.7.3\mingw\mkspecs\features\default_pre.prf:
..\..\..\..\QtSDK\Desktop\Qt\4.7.3\mingw\mkspecs\features\win32\default_pre.prf:
..\..\..\..\QtSDK\Desktop\Qt\4.7.3\mingw\mkspecs\features\debug.prf:
..\..\..\..\QtSDK\Desktop\Qt\4.7.3\mingw\mkspecs\features\debug_and_release.prf:
..\..\..\..\QtSDK\Desktop\Qt\4.7.3\mingw\mkspecs\features\default_post.prf:
..\..\..\..\QtSDK\Desktop\Qt\4.7.3\mingw\mkspecs\features\win32\default_post.prf:
..\..\..\..\QtSDK\Desktop\Qt\4.7.3\mingw\mkspecs\features\win32\rtti.prf:
..\..\..\..\QtSDK\Desktop\Qt\4.7.3\mingw\mkspecs\features\win32\exceptions.prf:
..\..\..\..\QtSDK\Desktop\Qt\4.7.3\mingw\mkspecs\features\win32\stl.prf:
..\..\..\..\QtSDK\Desktop\Qt\4.7.3\mingw\mkspecs\features\shared.prf:
..\..\..\..\QtSDK\Desktop\Qt\4.7.3\mingw\mkspecs\features\warn_on.prf:
..\..\..\..\QtSDK\Desktop\Qt\4.7.3\mingw\mkspecs\features\qt.prf:
..\..\..\..\QtSDK\Desktop\Qt\4.7.3\mingw\mkspecs\features\win32\thread.prf:
..\..\..\..\QtSDK\Desktop\Qt\4.7.3\mingw\mkspecs\features\moc.prf:
..\..\..\..\QtSDK\Desktop\Qt\4.7.3\mingw\mkspecs\features\win32\windows.prf:
..\..\..\..\QtSDK\Desktop\Qt\4.7.3\mingw\mkspecs\features\resources.prf:
..\..\..\..\QtSDK\Desktop\Qt\4.7.3\mingw\mkspecs\features\uic.prf:
..\..\..\..\QtSDK\Desktop\Qt\4.7.3\mingw\mkspecs\features\yacc.prf:
..\..\..\..\QtSDK\Desktop\Qt\4.7.3\mingw\mkspecs\features\lex.prf:
..\..\..\..\QtSDK\Desktop\Qt\4.7.3\mingw\mkspecs\features\include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -spec ..\..\..\..\QtSDK\Desktop\Qt\4.7.3\mingw\mkspecs\win32-g++ -o Makefile bshuffle.pro

qmake_all: sub-libs-bshuffle-session-qmake_all sub-libs-print-settings-qmake_all sub-bshuffle-qmake_all FORCE

make_default: sub-libs-bshuffle-session-make_default sub-libs-print-settings-make_default sub-bshuffle-make_default FORCE
make_first: sub-libs-bshuffle-session-make_first sub-libs-print-settings-make_first sub-bshuffle-make_first FORCE
all: sub-libs-bshuffle-session-all sub-libs-print-settings-all sub-bshuffle-all FORCE
clean: sub-libs-bshuffle-session-clean sub-libs-print-settings-clean sub-bshuffle-clean FORCE
distclean: sub-libs-bshuffle-session-distclean sub-libs-print-settings-distclean sub-bshuffle-distclean FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-libs-bshuffle-session-install_subtargets sub-libs-print-settings-install_subtargets sub-bshuffle-install_subtargets FORCE
uninstall_subtargets: sub-libs-bshuffle-session-uninstall_subtargets sub-libs-print-settings-uninstall_subtargets sub-bshuffle-uninstall_subtargets FORCE

sub-libs-bshuffle-session-sub_Debug: libs\bshuffle-session\$(MAKEFILE)
	cd libs\bshuffle-session\ && $(MAKE) debug
sub-libs-print-settings-sub_Debug: libs\print-settings\$(MAKEFILE)
	cd libs\print-settings\ && $(MAKE) debug
sub-bshuffle-sub_Debug: bshuffle\$(MAKEFILE)
	cd bshuffle\ && $(MAKE) debug
debug: sub-libs-bshuffle-session-sub_Debug sub-libs-print-settings-sub_Debug sub-bshuffle-sub_Debug

sub-libs-bshuffle-session-sub_Release: libs\bshuffle-session\$(MAKEFILE)
	cd libs\bshuffle-session\ && $(MAKE) release
sub-libs-print-settings-sub_Release: libs\print-settings\$(MAKEFILE)
	cd libs\print-settings\ && $(MAKE) release
sub-bshuffle-sub_Release: bshuffle\$(MAKEFILE)
	cd bshuffle\ && $(MAKE) release
release: sub-libs-bshuffle-session-sub_Release sub-libs-print-settings-sub_Release sub-bshuffle-sub_Release

sub-libs-bshuffle-session-check: libs\bshuffle-session\$(MAKEFILE)
	cd libs\bshuffle-session\ && $(MAKE) check
sub-libs-print-settings-check: libs\print-settings\$(MAKEFILE)
	cd libs\print-settings\ && $(MAKE) check
sub-bshuffle-check: bshuffle\$(MAKEFILE)
	cd bshuffle\ && $(MAKE) check
check: sub-libs-bshuffle-session-check sub-libs-print-settings-check sub-bshuffle-check

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

