#ifndef PRINTSETTINGS_GLOBAL_H
#define PRINTSETTINGS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PRINTSETTINGS_LIBRARY)
#  define PRINTSETTINGSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PRINTSETTINGSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PRINTSETTINGS_GLOBAL_H
